//------------------------------------------------------------------------------
// <auto-generated>
//     VSTO host item glue for the Excel add-in.
//     Do not edit this file in the Visual Studio designer.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414

namespace ExcelShiftScroll
{
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(
        global::System.Security.Permissions.SecurityAction.Demand,
        Name = "FullTrust")]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.AddInBase
    {
        internal Microsoft.Office.Tools.CustomTaskPaneCollection CustomTaskPanes;
        internal Microsoft.Office.Tools.SmartTagCollection VstoSmartTags;

        internal Microsoft.Office.Interop.Excel.Application Application;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisAddIn(
            global::Microsoft.Office.Tools.Excel.ApplicationFactory factory,
            global::System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        protected override void Initialize()
        {
            base.Initialize();
            Application = GetHostItem<Microsoft.Office.Interop.Excel.Application>(
                typeof(Microsoft.Office.Interop.Excel.Application),
                "Application");
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            InitializeCachedData();
            InitializeControls();
            InitializeComponents();
            InitializeData();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        protected override void FinishInitialization()
        {
            InternalStartup();
            OnStartup();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        protected override void InitializeDataBindings()
        {
            BeginInitialization();
            BindToData();
            EndInitialization();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        private void InitializeCachedData()
        {
            if (DataHost == null || !DataHost.IsCacheInitialized)
            {
                return;
            }

            DataHost.FillCachedData(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        private void InitializeData()
        {
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        private void BindToData()
        {
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        private void BeginInitialization()
        {
            BeginInit();
            CustomTaskPanes.BeginInit();
            VstoSmartTags.BeginInit();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        private void EndInitialization()
        {
            VstoSmartTags.EndInit();
            CustomTaskPanes.EndInit();
            EndInit();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        private void InitializeControls()
        {
            CustomTaskPanes = Globals.Factory.CreateCustomTaskPaneCollection(
                null, null, "CustomTaskPanes", "CustomTaskPanes", this);
            VstoSmartTags = Globals.Factory.CreateSmartTagCollection(
                null, null, "VstoSmartTags", "VstoSmartTags", this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        private void InitializeComponents()
        {
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        protected override void OnShutdown()
        {
            VstoSmartTags.Dispose();
            CustomTaskPanes.Dispose();
            base.OnShutdown();
        }
    }

    internal sealed partial class Globals
    {
        private Globals()
        {
        }

        private static ThisAddIn thisAddIn;
        private static global::Microsoft.Office.Tools.Excel.ApplicationFactory factory;

        internal static ThisAddIn ThisAddIn
        {
            get { return thisAddIn; }
            set
            {
                if (thisAddIn != null)
                {
                    throw new System.NotSupportedException();
                }

                thisAddIn = value;
            }
        }

        internal static global::Microsoft.Office.Tools.Excel.ApplicationFactory Factory
        {
            get { return factory; }
            set
            {
                if (factory != null)
                {
                    throw new System.NotSupportedException();
                }

                factory = value;
            }
        }
    }
}
